apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-server
  selector:
    app: redis-server
