apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ruby-helloworld
  name: ruby-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      run: ruby-helloworld
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ruby-helloworld
    spec:
      containers:
      - image: gcr.io/ruby-helloworld-210915/ruby-helloworld:latest
        name: ruby-helloworld
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: REDIS_HOST
          value: "redis-server"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 4567
          protocol: TCP
        livenessProbe:
          httpGet:
              path: /
              port: 4567
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
              path: /
              port: 4567
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
