apiVersion: v1
kind: Service
metadata:
  labels:
    run: ruby-helloworld
  name: ruby-helloworld
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    run: ruby-helloworld
  type: LoadBalancer
